### ISSUE TITLE
Error while trying to convert Hyrule Rebalance v7.9

### ISSUE THREAD

**Issue by zizelle** [Nitr4m12/UltimateBoTWConverter#16]
Hello,

I just wanted to raise an issue because I wasn't able to find what was the origin of the error I get when I try to convert Hyrule Rebalance mod v7.9 from WiiU to Switch.

I use the last version of UBOTW (1.3.4) and the last version of bcml (3.10.1), updated with --force-reintsall option. 

When I convert, everything seem to work correctly until I get that error : 

_SSTR Armor_230_Lower.11
SSTR textures
SSTR
sparseResidency 0 sparseBinding 0 BlockHeightLog2 4
Texture original data not set
BSTR Armor_230_Lower.11
BSTR textures
BSTR
SSTR Armor_230_Lower.11
SSTR textures
SSTR
sparseResidency 0 sparseBinding 0 BlockHeightLog2 4
BSTR Armor_230_Lower.11
BSTR textures
BSTR
Saving data....
**Traceback (most recent call last):
  File "converter.py", line 319, in convert
    warnings = convert_mod(mod_path, False, True)
  File "C:\Users\RémiMézelle\AppData\Local\Programs\Python\Python38\lib\site-packages\bcml\dev.py", line 763, in convert_mod
    byml = oead.byml.from_binary(util.unyaz_if_needed(file.read_bytes()))
oead.InvalidDataError: Invalid header**_ 

Is it an error from the converter or could it be thatthe mod is not compatible to switch conversion ?

Any info would be much appreciated.
Kind regards !

**Comment by Nitr4m12** [comment]
This looks like an issue with the mod itself rather than the converter. It looks like some file is wrongly formatted, but I can't tell which just from the error
